/// <reference types="vite/client" />


// These are the types for the virtual modules generated by Vite plugins.
declare module 'virtual:transpiled-core-js' {
  const code: string;
  export default code;
}

declare module 'virtual:transpiled-core-dts' {
  const declaration: string;
  export default declaration;
}